name: Espresso Docker

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build_and_push_docker_image:
    name: Push Docker image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Generate docker metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ inputs.images }}

      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request'  }}
          tags: ${{ steps.metadata.outputs.tags  }}
          labels: ${{ steps.metadata.outputs.labels  }}
          platforms: linux/amd64,arm64
