name: Docker Images

on:
  push:
    branches:
      - main
      - release-*
      - integration
  pull_request:
  workflow_dispatch:

jobs:
  docker-l1:
    uses: ./.github/workflows/docker.yml
    with:
        images: ghcr.io/espressosystems/op-espresso-integration/l1
        context: ./ops-bedrock
        dockerfile: ./ops-bedrock/Dockerfile.l1
    secrets: inherit

  docker-l2:
    uses: ./.github/workflows/docker.yml
    with:
        images: ghcr.io/espressosystems/op-espresso-integration/l2
        context: ./ops-bedrock
        dockerfile: ./ops-bedrock/Dockerfile.l2
    secrets: inherit

  docker-stateviz:
    uses: ./.github/workflows/docker.yml
    with:
        images: ghcr.io/espressosystems/op-espresso-integration/stateviz
        context: .
        dockerfile: ./ops-bedrock/Dockerfile.stateviz
    secrets: inherit
