name: OP Node Docker Images

on:
  push:
    branches:
      - main
      - release-*
      - integration
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: espressosystems/op-espresso-integration
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build_and_push_docker_image:
    name: Push Docker image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Set up environment
        run: |
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_DATE=$(git show -s --format='%ct')
          IMAGE_TAGS=$GIT_COMMIT,latest
          echo "GIT_COMMIT=$GIT_COMMIT" >> "$GITHUB_ENV"
          echo "GIT_DATE=$GIT_DATE" >> "$GITHUB_ENV"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> "$GITHUB_ENV"
          cat "$GITHUB_ENV"

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          targets: op-node,op-batcher,op-proposer,op-geth-proxy
          push: ${{ github.event_name != 'pull_request'  }}
